" Generated by vim-plug
" 2023/8/5 10:37:53
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['coc.nvim'].commit = 'eba04ac7df3a24902a689ad5710cd156bdd963b8'
silent! let g:plugs['gruvbox-material'].commit = 'b17daceec6ed9a5fb46e0f293f2ac666c90e5459'
silent! let g:plugs['hop.nvim'].commit = '03f0434869f1f38868618198b5f4f2ab6d39aef2'
silent! let g:plugs['indent-blankline.nvim'].commit = '4541d690816cb99a7fc248f1486aa87f3abce91c'
silent! let g:plugs['jupynium.nvim'].commit = '0e55a378218a8f2260bc64561566d85a33636403'
silent! let g:plugs['markdown-preview.nvim'].commit = '02cc3874738bc0f86e4b91f09b8a0ac88aef8e96'
silent! let g:plugs['nvim-treesitter'].commit = '1c79da3300951e934f635eaf8703480b57644e7e'
silent! let g:plugs['tabular'].commit = '339091ac4dd1f17e225fe7d57b48aff55f99b23a'
silent! let g:plugs['vim-highlightedyank'].commit = 'fa3f57b097e9521ce41a66b6c7cf5d9adea70ea3'
silent! let g:plugs['vim-illuminate'].commit = 'a2907275a6899c570d16e95b9db5fd921c167502'
silent! let g:plugs['vim-lsp-cxx-highlight'].commit = '0e7476ff41cd65e55f92fdbc7326335ec33b59b0'
silent! let g:plugs['vim-plug'].commit = 'ca0ae0a8b1bd6380caba2d8be43a2a19baf7dbe2'
silent! let g:plugs['vim-smoothie'].commit = 'df1e324e9f3395c630c1c523d0555a01d2eb1b7e'

PlugUpdate!

