" Generated by vim-plug
" 2023/9/4 18:46:50
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['coc.nvim'].commit = 'fab97c7db68f24e5cc3c1cf753d3bd1819beef8f'
silent! let g:plugs['gruvbox-material'].commit = 'b5f8c6a6c1cda630c53b061b765068a0898d47a3'
silent! let g:plugs['hop.nvim'].commit = '03f0434869f1f38868618198b5f4f2ab6d39aef2'
silent! let g:plugs['indent-blankline.nvim'].commit = '4541d690816cb99a7fc248f1486aa87f3abce91c'
silent! let g:plugs['jupynium.nvim'].commit = 'ff0ffd84f78e7e13e2180b900bf1f41d162577ef'
silent! let g:plugs['markdown-preview.nvim'].commit = '02cc3874738bc0f86e4b91f09b8a0ac88aef8e96'
silent! let g:plugs['nvim-autopairs'].commit = 'a52fc6eeec116746110b703381777c46d89d9e27'
silent! let g:plugs['nvim-colorizer.lua'].commit = '36c610a9717cc9ec426a07c8e6bf3b3abcb139d6'
silent! let g:plugs['nvim-treesitter'].commit = 'ae88851cac32415c8239a04b7ee44d8f7625e186'
silent! let g:plugs['tabular'].commit = '339091ac4dd1f17e225fe7d57b48aff55f99b23a'
silent! let g:plugs['vim-highlightedyank'].commit = 'fa3f57b097e9521ce41a66b6c7cf5d9adea70ea3'
silent! let g:plugs['vim-illuminate'].commit = 'a2907275a6899c570d16e95b9db5fd921c167502'
silent! let g:plugs['vim-lsp-cxx-highlight'].commit = '0e7476ff41cd65e55f92fdbc7326335ec33b59b0'
silent! let g:plugs['vim-plug'].commit = 'ca0ae0a8b1bd6380caba2d8be43a2a19baf7dbe2'
silent! let g:plugs['vim-smoothie'].commit = 'df1e324e9f3395c630c1c523d0555a01d2eb1b7e'

PlugUpdate!

