" Generated by vim-plug
" 2026/3/15 11:56:56
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['auto-pairs'].commit = '89e7529eaaac766d27c8251fdf14ca50f48c5866'
silent! let g:plugs['coc.nvim'].commit = 'd2edf3f39befb28288f1ce0f066bdb95684deb92'
silent! let g:plugs['gruvbox-material'].commit = 'f5f912fbc7cf2d45da6928b792d554f85c7aa89a'
silent! let g:plugs['hop.nvim'].commit = '9c6a1dd9afb53a112b128877ccd583a1faa0b8b6'
silent! let g:plugs['indent-blankline.nvim'].commit = '005b56001b2cb30bfa61b7986bc50657816ba4ba'
silent! let g:plugs['jupynium.nvim'].commit = '144ab6e46d2b42264c16a4f3c780d88feb0a89e8'
silent! let g:plugs['markdown-preview.nvim'].commit = 'a923f5fc5ba36a3b17e289dc35dc17f66d0548ee'
silent! let g:plugs['nvim-colorizer.lua'].commit = '517df88cf2afb36652830df2c655df2da416a0ae'
silent! let g:plugs['nvim-treesitter'].commit = '684eeac91ed8e297685a97ef70031d19ac1de25a'
silent! let g:plugs['tabular'].commit = '12437cd1b53488e24936ec4b091c9324cafee311'
silent! let g:plugs['vim-highlightedyank'].commit = '285a61425e79742997bbde76a91be6189bc988fb'
silent! let g:plugs['vim-illuminate'].commit = '1fa4b23409e22a03823648e344c77f260e2572cb'
silent! let g:plugs['vim-plug'].commit = '904dac1530cfec0880cd44e4f7f206eb2e9e3247'
silent! let g:plugs['vim-smoothie'].commit = 'df1e324e9f3395c630c1c523d0555a01d2eb1b7e'

PlugUpdate!

